const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('host', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  updateSettings: (partial) => ipcRenderer.invoke('settings:update', partial),
  listSessions: () => ipcRenderer.invoke('session:list'),
  getSession: (id) => ipcRenderer.invoke('session:get', id),
  createSession: () => ipcRenderer.invoke('session:create'),
  deleteSession: (id) => ipcRenderer.invoke('session:delete', id),
  renameSession: (id, title) => ipcRenderer.invoke('session:rename', id, title),
  setSessionProject: (id, projectId) => ipcRenderer.invoke('session:setProject', id, projectId),
  setSessionPreset: (id, presetId) => ipcRenderer.invoke('session:setPreset', id, presetId),
  appendMessage: (id, message) => ipcRenderer.invoke('session:appendMessage', id, message),
  deleteLastMessage: (id) => ipcRenderer.invoke('session:deleteLastMessage', id),
  replaceMessages: (id, messages) => ipcRenderer.invoke('session:replaceMessages', id, messages),
  setActiveSession: (id) => ipcRenderer.invoke('session:setActive', id),
  listProjects: () => ipcRenderer.invoke('project:list'),
  createProject: (name) => ipcRenderer.invoke('project:create', name),
  deleteProject: (id) => ipcRenderer.invoke('project:delete', id),
  listPresets: () => ipcRenderer.invoke('preset:list'),
  createPreset: (name, prompt) => ipcRenderer.invoke('preset:create', name, prompt),
  updatePreset: (id, partial) => ipcRenderer.invoke('preset:update', id, partial),
  deletePreset: (id) => ipcRenderer.invoke('preset:delete', id),
  listSkills: () => ipcRenderer.invoke('skill:list'),
  getSkill: (id) => ipcRenderer.invoke('skill:get', id),
  createSkill: (name, description, body) => ipcRenderer.invoke('skill:create', name, description, body),
  updateSkill: (id, partial) => ipcRenderer.invoke('skill:update', id, partial),
  deleteSkill: (id) => ipcRenderer.invoke('skill:delete', id),
  getSkillFile: (id, relPath) => ipcRenderer.invoke('skill:getFile', id, relPath),
  dbPath: () => ipcRenderer.invoke('db:path'),
  setIgnoreMouse: (ignore) => ipcRenderer.send('window:setIgnoreMouse', ignore),
  onResetBubble: (cb) => ipcRenderer.on('bubble:reset', () => cb()),
  onOpenPanel: (cb) => ipcRenderer.on('panel:open', () => cb()),
  onWindowBlur: (cb) => ipcRenderer.on('window:blur', () => cb()),
  onStoreChanged: (cb) => ipcRenderer.on('store:changed', (_e, scope) => cb(scope)),
  runTool: (name, args) => ipcRenderer.invoke('tool:run', { name, args }),
  pickWorkspace: () => ipcRenderer.invoke('dialog:pickWorkspace'),
  listMcpTools: () => ipcRenderer.invoke('mcp:listTools'),
  listMcpServers: () => ipcRenderer.invoke('mcp:listServers'),
  reloadMcpServers: (mcpServers) => ipcRenderer.invoke('mcp:reload', mcpServers),
  onMcpStatusChanged: (cb) => ipcRenderer.on('mcp:statusChanged', (_e, payload) => cb(payload)),
  openSettings: () => ipcRenderer.send('settings:open'),
  openSessions: () => ipcRenderer.send('sessions:open'),
  hide: () => ipcRenderer.send('window:hide'),
  quit: () => ipcRenderer.send('window:quit'),
  toggleMaximize: () => ipcRenderer.send('window:toggleMaximize'),
  onMaximizeChanged: (cb) => ipcRenderer.on('window:maximizeChanged', (_e, isMax) => cb(isMax))
});
